### ISSUE TITLE
Issue with servers that grant players all recipes

### ISSUE THREAD

**Issue by oddlama** [ps-dps/Multitool#4]
Hi, I'm the author of vane, a plugin which (among other things) gives administrators the option to grant player access to each recipe automatically. Unfortunately a user has just reported a bug to me that when they use this datapack in combination with that functionality, each multitool is given to a playes whenever they join the server. This is when the plugin grants the player all unknown recipes (which shouldn't include a reward by design).

I don't have a lot of experience with datapacks, but it looks to me like you register the crafting result as a reward for an unlockable recipe, which is then rewarded to players each time they perform the craft (or something similar to that). Since this doesn't align with the original intent of minecraft's recipes, it leads to the aforementioned bug. I'm not sure whether there is a way to actually register "real" recipes in this datapack to prevent the issue but since there is unfortunately nothing I can do about this bug in vane I was hoping there would be a way to fix this upstream.

**Comment by PuckiSilver** [comment]
Hey!

Yes, a lot of data packs use recipes, that grant an achievement, that give you the data pack's custom item to create custom recipes for data packs. This is done because you can't add NBT to the output of a recipe and all data pack items - are just vanilla items with custom NBT.

You could fix it for this - and probably all other data packs, if you only grant unknown recipes in the minecraft namespace (so all recipes that start with `minecraft:`) instead of all unknown recipes.

The same problem occurs with simple "unlock all recipes" data packs like the one from [Vanilla Tweaks](https://vanillatweaks.net/picker/datapacks/) but a data pack like [this one](https://www.planetminecraft.com/data-pack/wasd-unlock-all-recipes/) are specifically designed for compatibility.

Hope this helps, if you need any additional information or have other ideas let me know!
~ PuckiSilver

**Comment by oddlama** [comment]
Thanks for the quick response :)

> This is done because you can't add NBT to the output of a recipe and all data pack items - are just vanilla items with custom NBT.

Ah I feared something like that might be the reason. So there's no way around it?

> You could fix it for this - and probably all other data packs, if you only grant unknown recipes in the minecraft namespace (so all recipes that start with `minecraft:`) instead of all unknown recipes.

That will introduce other bugs, since it should unlock all recipes including recipes registered by other plugins (which are in unknown namespaces). So there's no way to distinguish a real recipe from a datapack's "trigger recipe" right now.

> Hope this helps, if you need any additional information or have other ideas let me know!

Looks like there's just no inherent solution to the problem, because so much stuff is made of workarounds to mojangs limited "API" :P

A good solution that I can think of right now would be to use a common prefix for triggering recipes, for example let their identifier begin with an underscore `_` to denote an *internal* recipe. I've seen some datapacks do that, and it would make filtering easy while allowing datapacks to also expose true recipes that shouldn't be filtered. The only issue is that this will realistically never become widely adopted at this point in time.

The only way to fix "everything" at once this is to put the burden on the user and have them blacklist certain namespaces. Either way thanks for your time, I think this can be closed then.

**Comment by PuckiSilver** [comment]
Actually, most data packs, that add custom recipes use the Knowledge Book as the output since it's easiest to check - it automatically grants the advancement and you can safely clear it from the players inventory without actual items being lost.

You could check if the item resulting from the craft is 'illegal', so something like a knowledge book, a spawn egg, a command block, a structure void, ..., and then not grant that recipe (not sure how much work/performance cost this is on your end though).

**Comment by oddlama** [comment]
Coding it would be trivial in either case, but to keep maintenance at a minimum for both sides there would need to be some convention that can be relied upon. Some plugins use the knowledge book as a base item for custom items for example, so that heuristic can't be used either. Anything that isn't agreed upon by everyone can and will just lead to more issues down the line.

For vane that'll probably mean that the recipe unlocking will just stay incompatible with datapacks since there's no way to reliably detect what is compatible and what isn't. It's such a minor feature that any one having issues with it can just live without it. There's onlya very very small intersection of people who depend on both a datapack like this one and on recipe unlocking desparately (if at all). And those few probably won't have issues writing a simple datapack that does unlock exactly the stuff they need.

So I'll just add a notice for now that this can be a problem :)

**Comment by PuckiSilver** [comment]
Hey, it's me again, in 1.20 minecraft introduced a new advancement trigger and most data packs should in-time adapt to use the new trigger (`recipe_crafted` instead of `recipe_unlocked`)

Once most data packs use the new (better) system this shouldn't be a problem anymore and you can just grant all recipes

Since v4.1.2 Multitool uses the new system
