### ISSUE TITLE
Continuously spawns the multitool

### ISSUE THREAD

**Issue by TinnyTerr** [ps-dps/Multitool#5]
I am OP'ed, alone on a origins minecraft server. (A few datapacks to change colour of names) and it keeps on spawning them in my inventory after I throw them away

https://github.com/ps-dps/Multitool/assets/74470480/023e3579-099f-46f1-b628-d0acc158e584

Just to clarify, deoping does not help and it is the same for the mod and the datapack

**Comment by PuckiSilver** [comment]
Hey, because of how the data pack/mod is made, it doesn’t work with most primitively coded "Unlock all recipes" data packs like the one by vanilla tweaks.

Either remove anything that constantly unlocks all recipes or replace it with something like [this data pack](https://www.planetminecraft.com/data-pack/wasd-unlock-all-recipes/), which is made to be compatible with all these data packs

If you are not using anything like that, please further describe other mods or data packs you are using

**Comment by PuckiSilver** [comment]
Hey, I changed the way Multitool handles recipes so your issue shouldn't persist anymore with all versions v4.1.2 and above
https://modrinth.com/datapack/multitool/versions
